volumes:
  postgres_data:

networks:
  proxy:
    name: proxy
    external: true
  internal-django:
    name: internal-django

services:
  db:
    build: ./docker-postgres
    restart: always
    shm_size: 1024mb
    volumes:
      - postgres_data:/var/lib/postgresql/data # save all configs on container deletion
      - ./docker-postgres/init:/docker-entrypoint-init-db.d
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports: # TODO: remove in prod
      - 5432:5432
    networks:
      - internal-django

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:5432
    networks:
      - internal-django

  django:
    build: . 
    depends_on:
      - db
    post_start:
      - command: ["bash", "-c", "/docker-entrypoint-init.d/init.sh"]
    container_name: django
    networks:
      - proxy
      - internal-django
    environment:
      - WHOAMI_NAME=WSGI_Django
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.docker.localhost`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.services.django.loadbalancer.server.port=8000" 
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.secure-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.ip-allowlist.ipallowlist.sourceRange=127.0.0.1/32,192.168.0.0/16,10.0.0.0/8"
      - "traefik.http.routers.django.middlewares=secure-headers,ip-allowlist"
      - "traefik.http.routers.django.tls.certresolver=le"


secrets:
  db_password:
    file: db_password.secret.txt
