tls:
  stores:
    default:
      defaultCertificate:
        keyFile: /certs/cloudflare.key
        certFile: /certs/cloudflare.pem
  certificates:
    - certFile: /certs/cloudflare.pem
      keyFile: /certs/cloudflare.key
